---
- hosts: all
  remote_user: ubuntu
  become: true

  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  pre_tasks:
    - name: 'Installing all dependencies on remote host for ansible [raw]'
      raw: sudo apt-get -y install python3-apt aptitude

  roles:
    - ansible-common
