---

- name: 'Installing all dependencies on remote host for ansible'
  raw: sudo apt-get -y install python-simplejson aptitude

- name: 'Upgrade and Update system repositories'
  apt: upgrade=yes update_cache=yes
  become: true

- name: 'Install curl, vim, htop, ufw'
  apt:
    name: "{{ item }}"
  with_items:
    - curl
    - vim
    - htop
    - ufw
  become: true

# create custom user with sudo
# add public key authentication
# ssh hardening (port, only custom user, po kluczu)
# ufw firewall
# fail2ban 10 times wrong password, moje ip jest ignorowane
#--no-install-recommends
