---
- name: 'Disable all unnecessery services on server'
  systemd:
    name: '{{ item }}'
    enabled: no
  with_items: disabled_services

- name: 'Upgrade and Update system repositories'
  apt: upgrade=yes update_cache=yes

- name: 'Install utils software'
  apt:
    name: '{{ item }}'
  with_items: install_utils_packages

- name: 'Add your sudo user'
  user:
    name: '{{ sudo_user }}'
    shell: /bin/bash
    groups: 'sudo'
    password: '{{ sudo_user_password }}'
    update_password: on_create
    createhome: yes
    append: yes

- name: 'Set authorized key for sudo user copying it from current user (~/.ssh/id_rsa.pub)'
  authorized_key:
    user: '{{ sudo_user }}'
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  when: custom_public_key is undefined

- name: 'Set custom authorized key for sudo_user'
  authorized_key:
    user: '{{ sudo_user }}'
    state: present
    key: '{{ custom_public_key }}'
  when: custom_public_key is defined
